variable "aws_region" {}
variable "instance_type" {}
variable "key_pair_path" {}
variable "user_data_path" {}
variable "db_engine" {}
variable "engine_version" {}
variable "db_instance_class" {}
variable "db_identifier" {}
variable "db_name" {}
variable "db_username" {}
variable "db_password" {}
variable "db_skip_final_snapshot" {}
variable "db_backup_retention_period" {}
variable "pub_subnet_1_id" {}
variable "web_server_sg_id" {}
variable "rds_subnet_name" {}
variable "rds_sg_id" {}
variable "pub_subnet_2_id" {}
variable "vpc_id" {}
